name: deploy
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/WebBack
          git config --global --add safe.directory /home/WebBack
          git pull -f
          go mod tidy
          go build
          echo "${{ secrets.PASSWORD }}" | sudo -S systemctl stop nginx
          echo "${{ secrets.PASSWORD }}" | sudo -S service goweb stop
          echo "${{ secrets.PASSWORD }}" | sudo -S service goweb start
          echo "${{ secrets.PASSWORD }}" | sudo -S systemctl start nginx
